appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: cYIOnEIvDT4CxGexCE4SKbrl534DsvGUD/oFJoHW1f18dLOVpYsIRDOvFY4eznIkRoHXhg0uoTmAaq9mfoO1e617pb8PjNDGOgem0Dvmkz0Wc05/dVNLIwe+x6QecfEWrSIsDyWz4QOzjejPJ225m2123Bw+Hwq7vm4wXS/bwDN6EbleS3SXMpWGpTiKlQI8Fpx1NpU1PHmTdU5/AZWOe2C1r/064Bu3fd8H+30LHZPX0+Irl9ng8d1Nr2KWjGEqKoGehzOuhz0vDmvdxFv3SV45hzM57VGyqny+O/UekKH6U2rhZQzhFPkZnJozX6ev9tt4cJg5487GhWPP/wrxlZl8+oLsnU5f0l3M293jWmkyzqrqK1iQzi1VMfFrWuFWgoE1PRDnIPEcQwVbcBQ+ZSz+7/RqoJMNlpcM1voQMXxTnvXrA2bcd9LwfDSFwJ/zKXgq29TtIW8yTMcLdBkRjLjvB8G2jCofLcfyW8bVzaoqLbqIY2xb0SS/ZQR69yC3+/9UkzEDPQIvH03MpHIPngpkyvujW6zZqCeL0wlRYf4oVckRG/G48IVoEhwOlXkNNWCXvtaZY+EZa1eQMHiOD2UNExIlY7wWoXPznDyvV6WpSfJEoInWA7eLzBnU/G+UjjHdZzHz9l+sFdzF0GDNfm+Z8v4WSjrdsDJVclBoVgA=}
provider:
  win: azure
